<!DOCTYPE html>  
<html lang="en">  
    <head>
        <meta charset="UTF-8">
        <title>Form</title>
    </head>
    <body>
        <h1>Form for employees</h1>
         <form action="#" method="post">
                 <label for="name">Name:</label><br>
                 <input type="text" id="name" name="name" required><br><br>

                 <label for="Surname">Surname:</label><br>
                 <input type="text" id="Surname" name="Surname" required><br><br>

                 <label for="Department">Department:</label><br>
                 <input type="text" id="Department" name="Department" required><br><br>

                 <label for="City">City:</label><br>
                 <input type="text" id="City" name="City" required><br><br>

                 <input type="submit" value="Send">
                 <h2>your company email is this: </h2>
             </form>
    </body>
</html>